### ISSUE TITLE
Add Deliverables

### ISSUE THREAD

**Issue by rmccormick314** [Team-ARES-Airflow-Processing-Pipeline/Website#3]

**Comment by rmccormick314** [comment]
Added deliverables. Having difficulty with the different categories. Would like to add one category each for Team, Client, and Mentor meeting minutes.

**Comment by mexiquin** [comment]
> Would like to add one category each for Team, Client, and Mentor meeting minutes.

I've found that the "Categories" functionality will only work if the deliverables are implemented in "blog post" format. Right now they are just links to the pdf file, and it isn't a bad thing. For now it might be best to leave them as links until I can figure out how to implement custom blog features
